version: 2.1
jobs:
  build-and-test:
      executor:
        name: node/default
      steps:
        - checkout
        - node/with-cache:
            steps:
              - run: yarn install
              - run: yarn run format
              - run: "[[ -z $(git --no-pager diff -- . ':(exclude)yarn.lock' ':(exclude)yarn.lock') ]]"
              - run: yarn run test --passWithNoTests
              - run: export CI=1
  deploy:
    executor: win/default
    steps:
      - run: curl -X POST -d {} ${deploy_master}
  
orbs:
  node: circleci/node@3.0.0
  win: circleci/windows@2.3.0
workflows:
  test-deploy:
    jobs:
      - node/test
      - deploy:
        filters:
          branches:
            only: master
              
