version: 2.1
jobs:
  deploy:
    steps:
      - run:
          command: curl -X POST -d {} ${deploy_master}
  
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
      - deploy:
        filters:
          branches:
            only: master
