version: 2.1
jobs:
  prepare:
    docker:
      - image: 'cimg/base:stable'
    steps:
    - checkout
    - node/install:
        install-yarn: true
    - restore_cache:
        name: Restore node modules cache
        key: node_modules-{{ checksum "yarn.lock" }}
    - run:
        name: Add all dependencies
        command: yarn 
    - save_cache:
        name: Save node modules cache
        key: node_modules-{{ checksum "yarn.lock" }}
        paths:
          - node_modules

  build-and-test:
      docker:
        - image: 'cimg/base:stable'
      steps:
        - checkout
        - node/install:
            install-yarn: true
        - restore_cache:
            name: Restore node modules cache
            key: node_modules-{{ checksum "yarn.lock" }}
        - run:
            command: yarn format
            name: Format all the files
        - run:
            command: yarn test --passWithNoTests
            name: Run all the tests

  deploy-to-netlify:
    docker:
      - image: cimg/base:2020.10
    steps:
      - checkout
      - run: curl -X POST -d {} ${deploy_master}
  
orbs:
  node: circleci/node@4.1.0

workflows:
  test-deploy:
    jobs:
      - prepare
      - build-and-test:
          requires:
            - prepare
      - deploy-to-netlify:
          filters:
            branches:
              only: master
          requires:
            - build-and-test