version: 2.1
jobs:
  build-and-test:
      docker:
        - image: 'cimg/base:stable'
      steps:
        - checkout
        - node/install:
            install-yarn: true
        - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
        - run:
            command: yarn install --immutable
            name: Add all dependencies
        - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
        - run:
            command: yarn format
            name: Format all the files
        - run:
            command: yarn test --passWithNoTests
            name: Run all the tests

  deploy-to-netlify:
    docker:
      - image: cimg/base:2020.10
    steps:
      - checkout
      - run: curl -X POST -d {} ${deploy_master}
  
orbs:
  node: circleci/node@4.1.0

workflows:
  test-deploy:
    jobs:
      - build-and-test
      - deploy-to-netlify:
          filters:
            branches:
              only: master
          requires:
            - build-and-test